[environment]
# project-root is used to find foundry.toml and use it's configuration as well.
project_root = "/home/enzoevers/smart-contract-formal-verification"
security_scans_rel_path = "./security-scans"
source_rel_path = "./src/smart-contracts"
remappings = [
    "ds-test/=libs/forge-std/lib/ds-test/src/",
    "forge-std/=libs/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@smart-contracts=src/smart-contracts/",
]
solc_version = "0.8.17"

[report]
report_output_rel_path = "./report"

# [[report.contract]]
# name = "VeriToken"
# report_custom_name = ""

[[report.contract]]
name = "VeriAuctionTokenForEth_problems"
report_custom_name = ""

[mythril]
enabled = false

[slither]
enabled = true

[smtchecker]
enabled = false
